// <auto-generated />
namespace ELibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _do : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_do));
        
        string IMigrationMetadata.Id
        {
            get { return "201804202103203_do"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
